### ISSUE TITLE
CMD pops up then closes on click of exe

### ISSUE THREAD

**Issue by LurchMOD** [pryvyd9/AzgaarToCK3#2]

**Comment by pryvyd9** [comment]
hi, did you download the 1.2.1 version?
Which OS do you use?

**Comment by pryvyd9** [comment]
I added win-arm to 1.2.2 so you can try that if you have ARM CPU.

**Comment by LurchMOD** [comment]
> hi, did you download the 1.2.1 version? Which OS do you use?

I downloaded 1.2.1 and 1.2.2, and i use windows 10.

**Comment by pryvyd9** [comment]
Please, try 1.2.3. Should work now

**Comment by pryvyd9** [comment]
It should work now. Feel free to reopen if the issue persists.
